# Generated by Django 3.1.3 on 2020-11-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('initial_information', models.ImageField(upload_to='initial_information')),
                ('initial_feedback', models.CharField(choices=[('INTERESTED', 'interested'), ('NOT INTERESTED', 'not interested')], max_length=60)),
                ('initial_contact_1', models.CharField(blank=True, max_length=256)),
                ('initial_contact_2', models.CharField(blank=True, max_length=256)),
                ('initial_contact_3', models.CharField(blank=True, max_length=256)),
                ('agreement', models.ImageField(upload_to='agreement')),
                ('first_payment_by_cheque', models.BooleanField(default=False)),
                ('second_payment_by_cheque', models.BooleanField(default=False)),
                ('third_payment_by_cheque', models.BooleanField(default=False)),
            ],
        ),
    ]
