# Generated by Django 3.1.3 on 2020-11-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ploting', '0002_model1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model1',
        ),
        migrations.AddField(
            model_name='plot',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='post/thumbnail/%Y/%m/%d/'),
        ),
    ]
