# Generated by Django 3.1.3 on 2020-11-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ploting', '0004_auto_20201128_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='first_payment_cheque_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='initial_information_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='second_payment_cheque_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='status',
            field=models.CharField(choices=[('PREPURCHASE', 'Pre-Purchase'), ('PURCHASED', 'Purchase'), ('SOLD', 'Sold')], default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plot',
            name='third_payment_cheque_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
