# Generated by Django 3.1.3 on 2020-12-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ploting', '0005_auto_20201130_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='id_or_passport_page_1',
            field=models.ImageField(blank=True, null=True, upload_to='post/thumbnail/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='plot',
            name='id_or_passport_page_2',
            field=models.ImageField(blank=True, null=True, upload_to='post/thumbnail/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='plot',
            name='id_or_passport_page_3',
            field=models.ImageField(blank=True, null=True, upload_to='post/thumbnail/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='plot',
            name='relative_id_or_passport_page_1',
            field=models.ImageField(blank=True, null=True, upload_to='post/thumbnail/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='plot',
            name='relative_id_or_passport_page_2',
            field=models.ImageField(blank=True, null=True, upload_to='post/thumbnail/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='plot',
            name='seller_photo',
            field=models.ImageField(blank=True, null=True, upload_to='post/thumbnail/%Y/%m/%d/'),
        ),
    ]
